<?php
// DO NOT EDIT BY HAND — ScoutingAPI examples, generated by the export script. Edit the script + re-run.
// Quickstart: search vrbo stays. Run: php quickstart.php
$key = getenv("SCOUTINGAPI_KEY") ?: exit("Set SCOUTINGAPI_KEY=scout_...\n");
$q = http_build_query(["location" => "Split, HR", "platforms" => "vrbo", "limit" => 5]);
$ch = curl_init("https://api.scoutingapi.com/v1/search?" . $q);
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_HTTPHEADER => ["Authorization: Bearer " . $key],
]);
$body = curl_exec($ch);
$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
if ($code !== 200) { fwrite(STDERR, "HTTP $code: $body\n"); exit(1); }
foreach (json_decode($body, true)["data"] as $s) {
    echo $s["platform"] . " - " . $s["name"] . " - " . $s["price"] . "\n";
}
