# DO NOT EDIT BY HAND — ScoutingAPI examples, generated by the export script. Edit the script + re-run.
# Quickstart: search vrbo stays. Run: ruby quickstart.rb
require "net/http"
require "json"
require "uri"

key = ENV["SCOUTINGAPI_KEY"] or abort("Set SCOUTINGAPI_KEY=scout_...")
uri = URI("https://api.scoutingapi.com/v1/search")
uri.query = URI.encode_www_form(location: "Split, HR", platforms: "vrbo", limit: 5)
req = Net::HTTP::Get.new(uri)
req["Authorization"] = "Bearer #{key}"
res = Net::HTTP.start(uri.host, uri.port, use_ssl: true) { |h| h.request(req) }
abort("HTTP #{res.code}: #{res.body}") unless res.code == "200"
JSON.parse(res.body)["data"].each { |s| puts "#{s['platform']} - #{s['name']} - #{s['price']}" }
