# DO NOT EDIT BY HAND — StayingAPI examples, generated by the export script. Edit the script + re-run.
# Quickstart: search vrbo stays. Run: pip install -r requirements.txt && python quickstart.py
import os, requests

key = os.environ.get("STAYINGAPI_KEY")
if not key:
    raise SystemExit("Set STAYINGAPI_KEY=stay_...")

resp = requests.get(
    "https://api.stayingapi.com/v1/search",
    headers={"Authorization": f"Bearer {key}"},
    params={"location": "Split, HR", "platforms": "vrbo", "limit": 5},
    timeout=60,
)
resp.raise_for_status()
for stay in resp.json()["data"]:
    print(stay.get("platform"), "-", stay.get("name"), "-", stay.get("price"))
