#!/usr/bin/env bash
# DO NOT EDIT BY HAND — ScoutingAPI examples, generated by the export script. Edit the script + re-run.
# Quickstart: search vrbo stays and print the first few results.
set -euo pipefail
: "${SCOUTINGAPI_KEY:?Set SCOUTINGAPI_KEY=scout_...}"
curl -s "https://api.scoutingapi.com/v1/search" \
  -G --data-urlencode "location=Split, HR" \
  --data-urlencode "platforms=vrbo" \
  --data-urlencode "limit=5" \
  -H "Authorization: Bearer $SCOUTINGAPI_KEY" \
  | jq '.data[] | {platform, name, price}'
