#!/usr/bin/env bash
# DO NOT EDIT BY HAND — StayingAPI examples, generated by the export script. Edit the script + re-run.
# Quickstart: search vrbo stays and print the first few results.
set -euo pipefail
: "${STAYINGAPI_KEY:?Set STAYINGAPI_KEY=stay_...}"
curl -s "https://api.stayingapi.com/v1/search" \
  -G --data-urlencode "location=Split, HR" \
  --data-urlencode "platforms=vrbo" \
  --data-urlencode "limit=5" \
  -H "Authorization: Bearer $STAYINGAPI_KEY" \
  | jq '.data[] | {platform, name, price}'
