// DO NOT EDIT BY HAND — ScoutingAPI examples, generated by the export script. Edit the script + re-run.
// Quickstart: search vrbo stays. Run: go run main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
)

type Stay struct {
	Platform string  `json:"platform"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
}
type Envelope struct {
	Data []Stay `json:"data"`
}

func main() {
	key := os.Getenv("SCOUTINGAPI_KEY")
	if key == "" {
		log.Fatal("Set SCOUTINGAPI_KEY=scout_...")
	}
	u, _ := url.Parse("https://api.scoutingapi.com/v1/search")
	q := u.Query()
	q.Set("location", "Split, HR")
	q.Set("platforms", "vrbo")
	q.Set("limit", "5")
	u.RawQuery = q.Encode()
	req, _ := http.NewRequest("GET", u.String(), nil)
	req.Header.Set("Authorization", "Bearer "+key)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 {
		log.Fatalf("HTTP %d: %s", resp.StatusCode, body)
	}
	var env Envelope
	if err := json.Unmarshal(body, &env); err != nil {
		log.Fatal(err)
	}
	for _, s := range env.Data {
		fmt.Printf("%s - %s - %.0f\n", s.Platform, s.Name, s.Price)
	}
}
