// DO NOT EDIT BY HAND — ScoutingAPI examples, generated by the export script. Edit the script + re-run.
// Quickstart: search vrbo stays. Run: node quickstart.mjs
const KEY = process.env.SCOUTINGAPI_KEY;
if (!KEY) { console.error("Set SCOUTINGAPI_KEY=scout_..."); process.exit(1); }

const url = new URL("https://api.scoutingapi.com/v1/search");
url.searchParams.set("location", "Split, HR");
url.searchParams.set("platforms", "vrbo");
url.searchParams.set("limit", "5");

const resp = await fetch(url, { headers: { Authorization: `Bearer ${KEY}` } });
if (!resp.ok) throw new Error(`HTTP ${resp.status}: ${await resp.text()}`);
const { data, meta } = await resp.json();
for (const stay of data) console.log(stay.platform, "-", stay.name, "-", stay.price);
console.log("platforms:", (meta.platforms || []).join(", "));
